### ISSUE TITLE
getting java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter when trying to build js

### ISSUE THREAD

**Issue by mico** [asciinema/asciinema-player#134]
Following instructions from README
```
git clone https://github.com/asciinema/asciinema-player
cd asciinema-player
git co v2.6.1
git submodule update --init --recursive
lein cljsbuild once release
```
on last command getting error:
```
$ lein cljsbuild once release
Compiling ClojureScript...
Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/util.cljc:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
[...]
```
mac os x version 10.15.1
```
$ lein -v
Leiningen 2.9.3 on Java 10 Java HotSpot(TM) 64-Bit Server VM
```

the same result if I do `lein figwheel dev`
tried to add `:jvm-opts ["--add-modules" "java.xml.bind"]` to `project.clj` but it didn't help

**Comment by mico** [comment]
found solution: 
1. switched to java 10:
```
export JAVA_HOME=`/usr/libexec/java_home -v 10`
```
2. added `:jvm-opts ["--add-modules" "java.xml.bind"]` to project.clj before `:dependencies`

but this is not working for jdk 14
also I was using 2.6.1 version of asciinema-player
